name: Terraform Deploy AWS Infrastructure

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: Select Terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy AWS EC2 and S3 bucket
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: EC2

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply or Destroy
      run: |
        if [ "${{ github.event.inputs.terraform_action }}" == "apply" ]; then
          echo "Applying Terraform changes"
          terraform apply -auto-approve
        elif [ "${{ github.event.inputs.terraform_action }}" == "destroy" ]; then
          echo "Destroying Terraform infrastructure"
          terraform destroy -auto-approve
        else
          echo "Invalid Terraform action selected"
          exit 1
        fi
